# -*- coding: utf-8 -*-
"""week09_exercise.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HEB4gkUgmT4afC4t6mgClxoxct2poCKK
"""

import streamlit as st
import pandas as pd
import plotly.express as px

# --------------------------------------------------
# Page configuration
# --------------------------------------------------
st.set_page_config(
    page_title="World Happiness Dashboard",
    page_icon="🌍",
    layout="wide"
)

# --------------------------------------------------
# Load data
# --------------------------------------------------
df = pd.read_csv("world_happiness_2023.csv")

df.columns = [
    'Country',
    'Region',
    'Score',
    'GDP',
    'Social_Support',
    'Life_Expectancy',
    'Freedom',
    'Generosity',
    'Corruption'
]

# --------------------------------------------------
# Sidebar
# --------------------------------------------------
with st.sidebar:
    st.header("Filters")

    regions = ["All"] + sorted(df["Region"].unique().tolist())

    selected_region = st.selectbox(
        "Select Region",
        regions
    )

# Apply filter
if selected_region != "All":
    filtered_df = df[df["Region"] == selected_region]
else:
    filtered_df = df.copy()

# --------------------------------------------------
# Title
# --------------------------------------------------
st.title("🌍 World Happiness Dashboard")
st.markdown("Explore happiness scores and related indicators around the world.")

# --------------------------------------------------
# KPI Row
# --------------------------------------------------
col1, col2, col3 = st.columns(3)

with col1:
    st.metric(
        "Countries",
        len(filtered_df)
    )

with col2:
    st.metric(
        "Average Happiness",
        round(filtered_df["Score"].mean(), 2)
    )

with col3:
    st.metric(
        "Highest Score",
        round(filtered_df["Score"].max(), 2)
    )

# --------------------------------------------------
# Chart Row
# --------------------------------------------------
left, right = st.columns(2)

# --------------------------------------------------
# Chart 1
# Top Happiness Scores
# --------------------------------------------------
with left:

    top15 = (
        filtered_df
        .nlargest(15, "Score")
        .sort_values("Score")
    )

    fig1 = px.bar(
        top15,
        x="Score",
        y="Country",
        orientation="h",
        color="Score",
        color_continuous_scale="Blues",
        title="Top 15 Happiest Countries"
    )

    fig1.update_layout(height=500)

    st.plotly_chart(fig1, use_container_width=True)

# --------------------------------------------------
# Chart 2
# GDP vs Happiness
# --------------------------------------------------
with right:

    fig2 = px.scatter(
        filtered_df,
        x="GDP",
        y="Score",
        color="Region",
        hover_name="Country",
        title="GDP and Happiness Relationship"
    )

    fig2.update_layout(height=500)

    st.plotly_chart(fig2, use_container_width=True)

# --------------------------------------------------
# Chart 3 (Class Exercise)
# Diverging colour scale
# --------------------------------------------------

st.subheader("Generosity by Country (Diverging Scale)")

top20_generosity = (
    filtered_df
    .sort_values("Generosity", ascending=False)
    .head(20)
)

fig3 = px.bar(
    top20_generosity,
    x="Country",
    y="Generosity",
    color="Generosity",
    color_continuous_scale="RdBu",
    color_continuous_midpoint=0,
    title="Top 20 Countries by Generosity"
)

# Midpoint annotation
fig3.add_annotation(
    x=0.5,
    y=0,
    xref="paper",
    yref="y",
    text="Midpoint = 0",
    showarrow=True
)

fig3.update_layout(
    xaxis_tickangle=-45,
    height=550
)

st.plotly_chart(fig3, use_container_width=True)